gist:
  noscript: false

gems:
  - jekyll-codepen

codepen:
  theme: 11473
  height: 600
  preview: false
  default_tab: result

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

