gist:
  noscript: false

url: "https://nestedsoftware.com"

plugins:
  - jekyll-seo-tag
  - jekyll-codepen
  - jekyll-gist
  - jekyll-sitemap

codepen:
  theme: 11473
  height: 600
  preview: false
  default_tab: result

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"

